server:
  port: 8083

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

logging:
  level:
    root: INFO
  file:
    name: /logs/Order-Service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7